---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Structure des ménages

```{r}
library(tidyverse)
library(haven)
library(dplyr)
library (gt) #Easily create presentation - ready display tables

#Chargement des données de ménages
res_deb <- read_dta("data/res_deb.dta")
res_m_a <- read_dta("data/res_m_a.dta")
  

```

## Caractéristiques socio-démographiques des ménage

```{r}
# Tableau de répartition des ménages selon les codes observatoires
tab <- res_deb %>%
  group_by(j0) %>%
  summarise(n = n_distinct(j5), .groups = "drop") %>%
  arrange(desc(n)) %>%
  mutate(
    Percent = round(n / sum(n) * 100, 1),
    j0 = as.character(j0)
  ) %>% 
  rename(Observatory = j0) %>%
  select(Observatory, n, Percent)

tab <- tab %>% 
  tibble::add_row(Observatory = "Total", n = sum(tab$n), Percent = sum(tab$Percent, na.rm = TRUE))

# Créer un tableau avec gt 
gt_tab <- gt(tab) %>% 
  tab_header( 
    title = "Répartition des ménages selon les codes observatoires",
    ) %>% 
  fmt_number( 
    columns = Percent, 
    decimals = 0, 
    suffixing = TRUE ) %>%
  tab_footnote( 
    footnote = "Percent (%)", 
    locations = cells_column_labels(columns = Percent) 
    )
gt_tab


```

Calculons la taille des ménages par observatoire

```{r}
hh_size <- res_m_a %>%
  group_by(j5) %>%
  mutate(hh_size = n()) %>%
  select(j5,hh_size) %>% 
  distinct(j5,hh_size)
  

```
