---
output: html_document
editor_options:
  chunk_output_type: console
editor:
  markdown:
    wrap: sentence
---

# Références {.unnumbered}

## Bibliographie

::: {#refs}
:::

## Liste des acronymes

AP : Aire Protégée

BETSAKA : Biodiversity-Economic Tradeoff and Synergy Assessments for Conservation Areas   

BTP : Bâtiment et Travaux Publics

CE : Cours Élémentaire

CERED : Centre d'Études et de Recherches Économiques pour le Développement

CITI rév.4 : Classification internationale type, par industrie, de toutes les branches d’activité économique, révision 4

CM : Chef de ménage

CM1 : Cours Moyen 1ère année

CM2 : Cours Moyen 2ème année

CP1 : Cours Préparatoire 1ère année

CP2 : Cours Préparatoire 2ème année

DGM : Direction Générale de la Météorologie

GPS : Global Positioning System

HIMO : Haute Intensité de Main-d'Œuvre

INSTAT : Institut National de la Statistique

IPC : Indice des Prix à la Consommation

IRD : Institut de Recherche pour le Développement

Nb : Nombre

OCDE : Organisation de Coopération et de Développement Économiques

OR : Observatoire rural

PR : Période de référence

RN : Route Nationale

SRA : Système de Riziculture Améliorée

SRI : Système de Riziculture Intensive

UC : Unité de Consommation
