profile:
  default: consolidated
  group:
    - [consolidated, marovoay, alaotra]

project: 
  type: book
  output-dir: docs
  post-render:
    - '"C:/Program Files/R/R-4.5.1/bin/x64/Rscript.exe" utils/add_cover_docx.R'
  
book: 
  site-url: https://github.com/BETSAKA/madagascar-rural-observatories-2025
  title: "Campagne 2025 des Observatoires ruraux d'Alaotra et Marovoay"
  subtitle: "Rapport d'enquêtes"
  author:
    - name: Veromanitra Ramizason
    - name: Bezaka Rivolala
    - name: Thierry Razanakoto
    - name: Holimalala Randriamanampisoa
    - name: Florent Bédécarrats
  repo-url: https://github.com/BETSAKA/madagascar-rural-observatories-2025
  date: today
          
bibliography: references.bib

execute: 
  warning: false
  error: false