project: 
  type: book
  output-dir: docs
  
book: 
  site-url: https://github.com/BETSAKA/madagascar-rural-observatories-2025
  title: "Campagne 2025 des Observatoires ruraux d'Alaotra et Marovoay"
  subtitle: "Rapport d'enquêtes"
  author: "Vero R., Florent B., Thierry R., Bezaka R., Holy R."
  repo-url: https://github.com/BETSAKA/madagascar-rural-observatories-2025
  date: "09/01/2026"
  chapters: 
    - index.qmd
    - 01_description.qmd
    - 04_structure_menages.qmd 
    - 05_habitat_niveau_de_vie.qmd 
    - 06_activites.qmd 
    - 07_foncier.qmd 
    - 08_agriculture.qmd 
    - 09_securite_alimentaire.qmd 
    - 10_rapport_environnement.qmd 
    - 11_cataclysme_catastrophe.qmd 
    - 12_insertion_projet.qmd 
    - 13_enquete_qualite.qmd 
    - 14_bibliographie.qmd
          
bibliography: references.bib

format: 
  html: 
    theme: cosmo
    code-fold: true

execute: 
  warning: false
  error: false
  